spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: fiap
    password: fiap

  h2:
    console:
      enabled:
        true
      path:
        /h2

extratoFile:
  extrato.json

portaH2:
  9090