INSERT INTO  TB_PRODUTO (NOME, VALOR, QUANTIDADE) VALUES('Televisao', 5000, 2);
INSERT INTO  TB_PRODUTO (NOME, VALOR, QUANTIDADE) VALUES('Notebook', 2500, 1);
INSERT INTO  TB_PRODUTO (NOME, VALOR, QUANTIDADE) VALUES('Playstation 4', 2500, 1);
INSERT INTO  TB_PRODUTO (NOME, VALOR, QUANTIDADE) VALUES('Home Theater', 1500, 1);
INSERT INTO  TB_PRODUTO (NOME, VALOR, QUANTIDADE) VALUES('Ar Condicionado', 4500, 1);

INSERT INTO  TB_CLIENTE (CPF, NOME) VALUES('309556410011','AARON FELIPE GRASSMANN');
INSERT INTO  TB_CLIENTE (CPF, NOME) VALUES('861083316026','AARON PAPA DE MORAIS');
INSERT INTO  TB_CLIENTE (CPF, NOME) VALUES('149477850035','ABNER GALLILEI MOREIRA BORGES');

INSERT INTO TB_CARTAO (NUMERO, AGENCIA, BANDEIRA, CODIGO_SEGURANCA, CONTA, MES_ANO_VALIDADE, NOME_TITULAR, TIPO_CARTAO) VALUES
('9999999999999999', '0001', 'MasterCard', '001', '1000-1', '12/2220',  'AARON FELIPE GRASSMANN', 0);

INSERT INTO TB_TRANSACAO (DATA_TRANSACAO, CLIENTE_CPF, VALOR_TOTAL, CARTAO_ID) VALUES (NOW(), '309556410011', 15000, 1);
INSERT INTO TB_TRANSACAO (DATA_TRANSACAO, CLIENTE_CPF, VALOR_TOTAL, CARTAO_ID) VALUES (NOW(), '861083316026', 21000, 1);
INSERT INTO TB_TRANSACAO (DATA_TRANSACAO, CLIENTE_CPF, VALOR_TOTAL, CARTAO_ID) VALUES (NOW(), '149477850035', 10000, 1);

INSERT INTO TB_TRANSACAO_PRODUTO VALUES(1, 1);
INSERT INTO TB_TRANSACAO_PRODUTO VALUES(1, 2);
INSERT INTO TB_TRANSACAO_PRODUTO VALUES(1, 3);

INSERT INTO TB_TRANSACAO_PRODUTO VALUES(2, 1);
INSERT INTO TB_TRANSACAO_PRODUTO VALUES(2, 2);
INSERT INTO TB_TRANSACAO_PRODUTO VALUES(2, 3);
INSERT INTO TB_TRANSACAO_PRODUTO VALUES(2, 4);
INSERT INTO TB_TRANSACAO_PRODUTO VALUES(2, 5);

INSERT INTO TB_TRANSACAO_PRODUTO VALUES(3, 1);