INSERT INTO  TB_PRODUTO (NOME, VALOR, QUANTIDADE) VALUES('Televisao', 5000, 2);
INSERT INTO  TB_PRODUTO (NOME, VALOR, QUANTIDADE) VALUES('Notebook', 2500, 1);
INSERT INTO  TB_PRODUTO (NOME, VALOR, QUANTIDADE) VALUES('Playstation 4', 2500, 1);
INSERT INTO  TB_PRODUTO (NOME, VALOR, QUANTIDADE) VALUES('Home Theater', 1500, 1);
INSERT INTO  TB_PRODUTO (NOME, VALOR, QUANTIDADE) VALUES('Ar Condicionado', 4500, 1);

INSERT INTO  TB_CLIENTE (CPF, NOME) VALUES('98765432100','Superman');
INSERT INTO  TB_CLIENTE (CPF, NOME) VALUES('98765432101','Batman');
INSERT INTO  TB_CLIENTE (CPF, NOME) VALUES('98765432102','Coringa');

INSERT INTO TB_TRANSACAO(DATA_TRANSACAO, CLIENTE_CPF) VALUES (NOW(), '98765432100');
INSERT INTO TB_TRANSACAO(DATA_TRANSACAO, CLIENTE_CPF) VALUES (NOW(), '98765432101');
INSERT INTO TB_TRANSACAO (DATA_TRANSACAO, CLIENTE_CPF) VALUES (NOW(), '98765432102');

INSERT INTO TB_TRANSACAO_PRODUTO VALUES(1, 1);
INSERT INTO TB_TRANSACAO_PRODUTO VALUES(1, 2);
INSERT INTO TB_TRANSACAO_PRODUTO VALUES(1, 3);

INSERT INTO TB_TRANSACAO_PRODUTO VALUES(2, 1);
INSERT INTO TB_TRANSACAO_PRODUTO VALUES(2, 2);
INSERT INTO TB_TRANSACAO_PRODUTO VALUES(2, 3);
INSERT INTO TB_TRANSACAO_PRODUTO VALUES(2, 4);
INSERT INTO TB_TRANSACAO_PRODUTO VALUES(2, 5);

INSERT INTO TB_TRANSACAO_PRODUTO VALUES(3, 1);